x="hello world" 
print(x)
print(type(x))
myName="pritha"
print(myName)
x=30
print(type(x))
print(x)
x=30.4
print(x)
print(type(x))
x=39J
print(x)
print(type(x))
x,y,z="apple","orange","banana"
print(x)
print(y)
print(z)
fruits=["apple","orange","banana"]
x,y,z=fruits
print(x)
print(y)
print(z)
print(len(fruits))
x=("apple","orange","banana")
print(x)
print(type(x))
print(len(x))
x=range(6)
print(x)
for i in range(1,10):
    print(i)
for i in range(1,10,2):
    print(i)
pritha=True
print(type(pritha))
userinfo={
    "name":"pritha",
    "age":20,
}
print(userinfo)
print(type(userinfo))

userinfo=[{"name":"pritha",
          "age":18},
          {"name":"priya",
          "age":20},
          {"name":"rohim",
          "age":20},
          {"name":"korim",
          "age":20}
]
print(userinfo)